# -*- coding: utf-8 -*-
"""DataScienceTensorFLow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_b0rjDl2g4qngqDidNAJu8fX2cbp73p
"""

import tensorflow as tf

from tensorflow import keras

import numpy as np

import matplotlib.pyplot as plt

data= keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = data.load_data()

train_images.shape, test_images.shape

train_labels.shape,test_labels

train_images[0]
plt.imshow(train_images[0])

train_images[5]
plt.imshow(train_images[5])

train_images[10000]
plt.imshow(train_images[10000])

train_images[59999]
plt.imshow(train_images[59999])

class_names = ["T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')

])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=10)

